package main

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCodeGenerator(t *testing.T) {
	tmpl := `package test

// generate:reset
type ResetableStruct struct {
    i     int
    str   string
    strP  *string
    s     []int
    m     map[string]string
    child *ResetableStruct
} 

type NonGenerated struct {
	ID string
}`

	expTmpl := `// Code generated by reset; DO NOT EDIT.

package test


func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}
	rs.i = 0
	rs.str = ""
	if rs.strP != nil { *rs.strP = "" }
	rs.s = rs.s[:0]
	clear(rs.m)
	if resetter, ok := interface{}(rs.child).(interface{ Reset() }); ok && rs.child != nil { 
		resetter.Reset() }
}`
	testDir := t.TempDir()
	path := filepath.Join(testDir, "test.go")
	err := os.WriteFile(path, []byte(tmpl), 0644)
	require.NoError(t, err)
	paths, err := getPaths(testDir)
	require.NoError(t, err)
	f := token.NewFileSet()
	pathData := make(map[string]pkgData)
	for _, path := range paths {
		f, err := parser.ParseFile(f, path, nil, parser.ParseComments)
		require.NoError(t, err)
		data := inspectFile(f)
		if len(data) > 0 {
			p := filepath.Dir(path)
			pkg := pathData[p]
			if pkg.Name == "" {
				pkg.Name = f.Name.Name
			}
			pkg.Data = append(pkg.Data, data...)
			pathData[p] = pkg
		}
	}
	writeFiles(pathData)
	expGenFile := filepath.Join(testDir, nameFile)
	assert.FileExists(t, expGenFile)
	content, err := os.ReadFile(expGenFile)
	require.NoError(t, err)
	genData := string(content)
	assert.Equal(t, strings.TrimSpace(expTmpl), strings.TrimSpace(genData))
	assert.NotContains(t, genData, "func (rs *NonGenerated) Reset()")
}
